spring:
  application:
    name: book-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: book-service
    config:
      uri: http://config-server:8888
  jwt:
    secret: "szll3hCCGHtb57UYoWqKMB8Hs5rXFOaCoes+b7DFCPhRXcnMDxjjZX7Pl43d6WTbuzLxwXGsPZMA5ZAaqPyxkw=="
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb # Corrected
    username: bereketab24
    password: bereketab24
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    mongodb:
      uri: mongodb://mongo:27017/Library_img # Corrected
server:
  port: 8082