spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: gateway
    config:
      uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/register,/api/v1/login
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/api/v1/admin/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
  jwt:
    secret: "szll3hCCGHtb57UYoWqKMB8Hs5rXFOaCoes+b7DFCPhRXcnMDxjjZX7Pl43d6WTbuzLxwXGsPZMA5ZAaqPyxkw=="

server:
  port: 8080