spring:
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: user-service
    config:
      uri: http://localhost:8888
  jwt:
    secret: "szll3hCCGHtb57UYoWqKMB8Hs5rXFOaCoes+b7DFCPhRXcnMDxjjZX7Pl43d6WTbuzLxwXGsPZMA5ZAaqPyxkw=="
  datasource:
    url: jdbc:postgresql://localhost:5555/usersDB
    username: bereketab24
    password: bereketab24
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
server:
  port: 8081
resilience4j:
  circuitbreaker:
    instances:
      bookService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
