spring:
  application:
    name: user-service
  cloud:
    consul:
      host: consul # Corrected
      port: 8500
      discovery:
        service-name: user-service
    config:
      uri: http://config-server:8888 # Corrected
  jwt:
    secret: "szll3hCCGHtb57UYoWqKMB8Hs5rXFOaCoes+b7DFCPhRXcnMDxjjZX7Pl43d6WTbuzLxwXGsPZMA5ZAaqPyxkw=="
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb # Corrected
    username: bereketab24
    password: bereketab24
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
resilience4j:
  circuitbreaker:
    instances:
      bookService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
